### ISSUE TITLE
Cannot execute Testerina samples by being inside examples folder against ballerina-platform-linux-installer-x64-0.970.0.beta1 installer

### ISSUE THREAD

**Issue by ShanikaWickramasinghe** [ballerina-platform/ballerina-examples#251]
**Environment**

ballerina-platform-linux-installer-x64-0.970.0.beta1.rpm (2018/04/19)

**Description:**
Install ballerina platform using ballerina-platform-linux-installer-x64-0.970.0.beta1 installer
Run the below command to execute the sample
Go inside /ballerina-examples/examples$ and execute

ballerina test testerina-before-after-suite/testerina-before-after-suite.bal

Obeserved the below exception

---------------------------------------------------------------------------
    T E S T S
---------------------------------------------------------------------------
ballerina: cannot find file 'testerina-before-after-suite/testerina-before-after-suite.bal'
Can't load log handler "org.ballerinalang.logging.handlers.DefaultLogFileHandler"
java.nio.file.AccessDeniedException: /opt/Ballerina/ballerina-platform-0.970.0-beta1/logs/bre.log.lck
java.nio.file.AccessDeniedException: /opt/Ballerina/ballerina-platform-0.970.0-beta1/logs/bre.log.lck
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:84)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newFileChannel(UnixFileSystemProvider.java:177)
	at java.nio.channels.FileChannel.open(FileChannel.java:287)
	at java.nio.channels.FileChannel.open(FileChannel.java:335)
	at java.util.logging.FileHandler.openFiles(FileHandler.java:478)
	at java.util.logging.FileHandler.<init>(FileHandler.java:281)
	at org.ballerinalang.logging.handlers.DefaultLogFileHandler.<init>(DefaultLogFileHandler.java:30)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at java.lang.Class.newInstance(Class.java:442)
	at java.util.logging.LogManager$5.run(LogManager.java:966)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.util.logging.LogManager.loadLoggerHandlers(LogManager.java:958)
	at java.util.logging.LogManager.initializeGlobalHandlers(LogManager.java:1578)
	at java.util.logging.LogManager.access$1500(LogManager.java:145)
	at java.util.logging.LogManager$RootLogger.accessCheckedHandlers(LogManager.java:1667)
	at java.util.logging.Logger.getHandlers(Logger.java:1777)
	at java.util.logging.Logger.log(Logger.java:735)
	at org.slf4j.impl.JDK14LoggerAdapter.log(JDK14LoggerAdapter.java:582)
	at org.slf4j.impl.JDK14LoggerAdapter.error(JDK14LoggerAdapter.java:559)
	at org.ballerinalang.launcher.Main.main(Main.java:80)

**please note that sample succesfully pass if run the command
ballerina test testerina-before-after-suite/testerina-before-after-suite.bal
by being inside ballerina-examples/examples/testerina-before-after-suite$ and fails if run by being inside examples folder**

**Comment by uthaiyashankar** [comment]
Similar comment as in https://github.com/ballerina-platform/ballerina-examples/issues/249

**Comment by yasassri** [comment]
This is not specific to testerina. This is a permission issue in OS level due to current log location of the ballerina distribution. This will be solved when log file is removed from the distribution.
