### ISSUE TITLE
when invoking the jms-queue-message-producer, the message broker throws an error

### ISSUE THREAD

**Issue by shavantha** [ballerina-platform/ballerina-examples#595]
**Description:**
when running jms-queue-message-producer/ the message broker throws an error

Setup
java :1.8.0_161
windows 7 professional
ballerina installer beta17

**Steps to reproduce:**
1.start the broker using broker.bat
2.rum the command ballerina run jms-queue-message-producer/
3.Check the broker logs

```
C:\ballerina\message-broker\message-broker-0.1.66\bin>broker.bat
[2018-04-26 12:50:23,873] INFO {io.ballerina.messaging.broker.auth.authentication.AuthenticatorFactory} -  Initializing au
thenticator: io.ballerina.messaging.broker.auth.authentication.authenticator.JaasAuthenticator
[2018-04-26 12:50:24,091] INFO {org.wso2.carbon.metrics.core.config.model.JmxReporterConfig} -  Creating JMX reporter for
Metrics with domain 'io.ballerina.messaging.broker'
[2018-04-26 12:50:24,497] INFO {org.wso2.carbon.metrics.core.reporter.impl.AbstractReporter} -  Started JMX reporter for M
etrics
[2018-04-26 12:50:24,497] INFO {io.ballerina.messaging.broker.core.BrokerImpl$BrokerHelper} -  Starting message delivery t
hreads.
[2018-04-26 12:50:24,497] INFO {io.ballerina.messaging.broker.core.task.TaskExecutorService} -  Starting task manager. Tas
k count 0
[2018-04-26 12:50:24,653] INFO {io.ballerina.messaging.broker.amqp.Server$ServerHelper} -  Listening AMQP on localhost:567
2
[2018-04-26 12:50:24,699] INFO {io.ballerina.messaging.broker.amqp.Server$ServerHelper} -  Listening AMQP/TLS on localhost
:8672
[2018-04-26 12:50:24,715] INFO {org.wso2.msf4j.MicroservicesRunner} -  Microservices server started in 608ms
[2018-04-26 12:50:24,715] INFO {io.ballerina.messaging.broker.rest.BrokerRestServer$BrokerRestRunnerHelper} -  Broker admi
n service started
[2018-04-26 12:50:24,715] INFO {org.wso2.transport.http.netty.listener.ServerConnectorBootstrap$HTTPServerConnector} -  HT
TP(S) Interface starting on host 0.0.0.0 and port 9000
[2018-04-26 12:50:37,728] WARN {io.ballerina.messaging.broker.amqp.codec.handlers.AmqpDecoder} -  Exception while handling
 request
java.io.IOException: An existing connection was forcibly closed by the remote host
        at sun.nio.ch.SocketDispatcher.read0(Native Method)
        at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:43)
        at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
        at sun.nio.ch.IOUtil.read(IOUtil.java:192)
        at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
        at io.netty.buffer.PooledUnsafeDirectByteBuf.setBytes(PooledUnsafeDirectByteBuf.java:288)
        at io.netty.buffer.AbstractByteBuf.writeBytes(AbstractByteBuf.java:1108)
        at io.netty.channel.socket.nio.NioSocketChannel.doReadBytes(NioSocketChannel.java:345)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:126)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:645)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:580)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:497)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:459)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:886)
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
        at java.lang.Thread.run(Thread.java:748)

```

**Comment by shavantha** [comment]
this was due to the fact that the queue message producer stops when running and the error occurs at that time
